### ISSUE TITLE
Logic Error: Castalist

### ISSUE THREAD

**Issue by kuzi117** [lurch9229/Ape-Escape-Tracker#23]
![image](https://github.com/user-attachments/assets/fff13733-8dbe-49f6-afbf-914bc1dc9d99)
I captured Castalist while having the club, the flyer, the RC car, and the net (I got the punch afterwards). The tracker believes it to still be unobtainable.

**Comment by Thedragon005** [comment]
The logic for Swimming excluded the normal WaterNet from the rules and only took into account the Progressive Water Net.
Corrected the rules to include Normal Water Net OR Progressive Water net for CanSwim, CanDive and CanWaterCatch.
Should be fixed in version 0.4.4
